export const InitPosts = [
  {
    id: 1,
    title: 'How reading changes your perspective',
    image: '/src/assets/post1.webp',
    author: 'Admin',
    date: 'Mar 22, 2023',
    readTime: '1 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 9,
    likeClass: '',
    views: 470,
    comments: 0,
    isShow: false,
  },
  {
    id: 2,
    title: 'The art of writing',
    image: '/src/assets/post2.webp',
    author: 'Admin',
    date: 'Mar 23, 2023',
    readTime: '2 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 6,
    likeClass: '',
    views: 199,
    comments: 0,
    isShow: false,
  },
  {
    id: 3,
    title: 'You want your child to read these books',
    image: '/src/assets/post3.webp',
    author: 'Admin',
    date: 'Mar 25, 2023',
    readTime: '3 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 5,
    likeClass: '',
    views: 98,
    comments: 0,
    isShow: false,
  },
  {
    id: 4,
    title: '“The Traitor’s Daughter”',
    image: '/src/assets/post4.webp',
    author: 'Admin',
    date: 'Mar 25, 2023',
    readTime: '3 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 3,
    likeClass: '',
    views: 91,
    comments: 0,
    isShow: false,
  },
  {
    id: 5,
    title: '8 must-read books',
    image: '/src/assets/post5.webp',
    author: 'Admin',
    date: 'Mar 25, 2023',
    readTime: '3 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 3,
    likeClass: '',
    views: 116,
    comments: 0,
    isShow: false,
  },
  {
    id: 6,
    title: 'My new digital reading habits',
    image: '/src/assets/post6.webp',
    author: 'Admin',
    date: 'Mar 25, 2023',
    readTime: '3 min read',
    content:
      'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
    likes: 1,
    likeClass: '',
    views: 57,
    comments: 0,
    isShow: false,
  },
]
